var myFullName;
console.log(myFullName);
myFullName="Prathmesh choudhari";
console.log(myFullName);
myFullName="Prathmesh Appaso Choudhari";
console.log(myFullName);
var myLove="I Love Only JS";
console.log(myLove);
var firstName="prathmesh";
var lastName="Choudhari";
var age="22";
var address="Sangola";
var pin_code="413307";
var gender="Male";
var is_married="No";
console.log("Name :"+firstName +" "+ lastName);
console.log("Age :" +age );
console.log("Address :" + address);
console.log("Pin Code :" +pin_code );
console.log("Gender :" + gender);
console.log("Is Married :" + is_married);